### ISSUE TITLE
waiting after casting soaring leap staff causes page to become unresponsive 

### ISSUE THREAD

**Issue by yegeniy** [red-kangaroo/wanderer#2]
There may be an infinite loop in this while loop, but I couldn't figure out how `x` and `y` are assigned so I'm not sure:

https://github.com/red-kangaroo/wanderer/blob/bda66e183f99d10831f1494d649a9c1566fe158c/src/Wanderer.html#L2473-L2477

<img width="446" alt="image" src="https://user-images.githubusercontent.com/292802/89231611-a9a13c80-d5b3-11ea-961b-77000675e2ef.png">

----

By the way, excellent game! Thank you for the simple interface and limited input set. I've been looking for something like this to play around with training an AI player.

**Comment by red-kangaroo** [comment]
Yeah, that's an infinite loop as the player keeps jumping in place, thank you.

Training an AI player sounds pretty interesting!

**Comment by yegeniy** [comment]
Thanks, I'll ping you if I get one working that just makes random moves 😄
